'use client';

import React, { useMemo } from 'react';
import { useScanStore } from '@/store/use-scan-store';
import { useLocale } from 'next-intl';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Loader2, Terminal, Sparkles, FileText, BarChart2, ShieldAlert, Info } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../ui/card';
import { Button } from '../ui/button';

export default function ExecutiveSummaryView() {
  const { 
    scanResult, 
    fetchExecutiveSummary, 
    executiveSummaryCache 
  } = useScanStore();
  const locale = useLocale();
  
  const cacheKey = useMemo(() => `summary-${locale}`, [locale]);

  const handleGenerateSummary = () => {
    if (scanResult) {
      fetchExecutiveSummary(scanResult, locale);
    }
  };

  const cacheEntry = executiveSummaryCache.get(cacheKey);
  const loading = cacheEntry?.status === 'loading';
  const error = cacheEntry?.status === 'error' ? cacheEntry.error : null;
  const data = cacheEntry?.status === 'loaded' ? cacheEntry.data : null;

  const formatMarkdown = (text: string = '') => {
    return text
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .split('\n')
      .map(line => line.trim())
      .filter(line => line.length > 0)
      .map(line => `<p>${line}</p>`)
      .join('');
  };
  
  const formatFinding = (text: string = '') => {
    return text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  };

  const generatingText = locale === 'es' ? 'Generando resumen...' : 'Generating summary...';
  const errorTitle = locale === 'es' ? 'Error' : 'Error';

  const mainTitle = locale === 'es' ? 'Resumen Ejecutivo' : 'Executive Summary';
  const mainDescription = locale === 'es' ? 'Un resumen de alto nivel de los resultados del escaneo, generado por IA.' : 'A high-level summary of the scan results, generated by AI.';
  const assessmentTitle = locale === 'es' ? 'Evaluación General de Seguridad' : 'Overall Security Assessment';
  const findingsTitle = locale === 'es' ? 'Principales Hallazgos Críticos' : 'Key Critical Findings';
  const recommendationsTitle = locale === 'es' ? 'Recomendaciones Estratégicas' : 'Strategic Recommendations';
  const generateButtonText = locale === 'es' ? 'Generar Resumen' : 'Generate Summary';
  const reGenerateButtonText = locale === 'es' ? 'Volver a Generar' : 'Re-generate';

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
             <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <div>
                    <CardTitle>{mainTitle}</CardTitle>
                    <CardDescription>{mainDescription}</CardDescription>
                </div>
                <Button onClick={handleGenerateSummary} disabled={loading}>
                    {loading ? (
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                        <Sparkles className="mr-2 h-4 w-4" />
                    )}
                    {loading ? generatingText : (data ? reGenerateButtonText : generateButtonText)}
                </Button>
            </div>
        </CardHeader>
        <CardContent>
            <Alert variant='default' className="items-center border-blue-500/50 text-blue-700 dark:text-blue-300 [&>svg]:text-blue-600 dark:[&>svg]:text-blue-400 bg-blue-500/10">
                <Info className="h-4 w-4" />
                <AlertDescription className='font-medium text-sm text-left'>
                    {locale === 'es' ? 'Para obtener el mejor resumen, escanea primero los CVEs. El resumen generado se incluirá en los informes PDF y HTML.' : 'For the best summary, scan for CVEs first. The generated summary will be included in PDF and HTML reports.'}
                </AlertDescription>
            </Alert>

             {error && (
                <Alert variant="destructive" className="mt-4">
                    <Terminal className="h-4 w-4" />
                    <AlertTitle>{errorTitle}</AlertTitle>
                    <AlertDescription>{error}</AlertDescription>
                </Alert>
            )}
        </CardContent>
      </Card>

      {loading && !data && (
           <Card>
               <CardContent className="flex flex-col items-center justify-center space-y-4 p-8 text-center min-h-[200px]">
                  <Loader2 className="h-12 w-12 animate-spin text-primary" />
                  <h2 className="text-xl font-semibold">{locale === 'es' ? 'Generando resumen...' : 'Generating summary...'}</h2>
                  <p className="text-muted-foreground">{locale === 'es' ? 'Esto puede tardar un momento...' : 'This may take a moment...'}</p>
              </CardContent>
          </Card>
      )}

      {data && (
        <>
            <Card>
                <CardHeader>
                <CardTitle className='flex items-center gap-2'>
                    <FileText className='h-6 w-6 text-primary' />
                    {assessmentTitle}
                </CardTitle>
                </CardHeader>
                <CardContent>
                <div
                    className="prose prose-sm dark:prose-invert max-w-full"
                    dangerouslySetInnerHTML={{ __html: formatMarkdown(data.overallAssessment) }}
                />
                </CardContent>
            </Card>

            <Card>
                <CardHeader>
                <CardTitle className='flex items-center gap-2'>
                    <BarChart2 className='h-6 w-6 text-primary' />
                    {findingsTitle}
                </CardTitle>
                </CardHeader>
                <CardContent>
                <ul className="list-disc space-y-2 pl-5">
                    {data.criticalFindings.map((finding, index) => (
                    <li key={index} className="text-sm" dangerouslySetInnerHTML={{ __html: formatFinding(finding) }} />
                    ))}
                </ul>
                </CardContent>
            </Card>
            
            <Card>
                <CardHeader>
                <CardTitle className='flex items-center gap-2'>
                    <ShieldAlert className='h-6 w-6 text-primary' />
                {recommendationsTitle}
                </CardTitle>
                </CardHeader>
                <CardContent>
                <ul className="list-disc space-y-2 pl-5">
                    {data.strategicRecommendations.map((rec, index) => (
                    <li key={index} className="text-sm" dangerouslySetInnerHTML={{ __html: formatFinding(rec) }} />
                    ))}
                </ul>
                </CardContent>
            </Card>
        </>
      )}
    </div>
  );
}